### ISSUE TITLE
Too many sections on the reading comfort scale

### ISSUE THREAD

**Issue by markdturner** [NewcastleRSE/CARA#2]

**Comment by mdsimpson42** [comment]
How many sections should there be?

**Comment by markdturner** [comment]
There are currently 5 but there should be 4. It's connected with #1 which is sort of tough to explain. We'll sort it on the next project hack day

**Comment by markdturner** [comment]
Fixed by 49bc93fa674e76a71ad541985e8a00f43a495b53
