### ISSUE TITLE
Text must appear exactly as it does on the paper version

### ISSUE THREAD

**Issue by markdturner** [NewcastleRSE/CARA#5]
Some words are underlined and the position of sentences is important

**Comment by mdsimpson42** [comment]
Do we have a copy of the paper version somewhere?

**Comment by markdturner** [comment]
I'm getting that sent over asap - they might need to scan it first

**Comment by markdturner** [comment]
Fixed by 49bc93fa674e76a71ad541985e8a00f43a495b53
